name: Snyk test Docker image
on: 
  push:
    branches: [master, radix, snyk_docker]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  snyk_test:
    name: Snyk test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Load openvds image
      uses: "./.github/actions/load_openvds_image"

    - name: Build docker image
      run: |
        tag=snyk
        docker build \
        -f Dockerfile \
        --build-arg OPENVDS_IMAGE=${{ env.OPENVDS_IMAGE_TAG }} \
        --tag $tag \
        .

    - name: Run Snyk to check Docker image for vulnerabilities
      id: docker-image-scan
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        image: snyk
        args: --file=Dockerfile
          --severity-threshold=high